<?php
/**
 * SysInvoiceDataSetsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * SysInvoiceDataSetsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SysInvoiceDataSetsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceId
     *
     * Haal een invoice op bij een organization
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_id  (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\EcedoERPCRMInterfaceReportModelOrganizationDto
     */
    public function sysInvoiceDataSetsGetByInvoiceId($organization_id, $invoice_id)
    {
        list($response) = $this->sysInvoiceDataSetsGetByInvoiceIdWithHttpInfo($organization_id, $invoice_id);
        return $response;
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceIdWithHttpInfo
     *
     * Haal een invoice op bij een organization
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_id  (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\EcedoERPCRMInterfaceReportModelOrganizationDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function sysInvoiceDataSetsGetByInvoiceIdWithHttpInfo($organization_id, $invoice_id)
    {
        $returnType = '\Swagger\Client\Model\EcedoERPCRMInterfaceReportModelOrganizationDto';
        $request = $this->sysInvoiceDataSetsGetByInvoiceIdRequest($organization_id, $invoice_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EcedoERPCRMInterfaceReportModelOrganizationDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EcedoERPCRMInterfaceApiErrorMessage400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EcedoERPCRMInterfaceApiErrorMessage401',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceIdAsync
     *
     * Haal een invoice op bij een organization
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_id  (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sysInvoiceDataSetsGetByInvoiceIdAsync($organization_id, $invoice_id)
    {
        return $this->sysInvoiceDataSetsGetByInvoiceIdAsyncWithHttpInfo($organization_id, $invoice_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceIdAsyncWithHttpInfo
     *
     * Haal een invoice op bij een organization
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_id  (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sysInvoiceDataSetsGetByInvoiceIdAsyncWithHttpInfo($organization_id, $invoice_id)
    {
        $returnType = '\Swagger\Client\Model\EcedoERPCRMInterfaceReportModelOrganizationDto';
        $request = $this->sysInvoiceDataSetsGetByInvoiceIdRequest($organization_id, $invoice_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sysInvoiceDataSetsGetByInvoiceId'
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_id  (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sysInvoiceDataSetsGetByInvoiceIdRequest($organization_id, $invoice_id)
    {
        // verify the required parameter 'organization_id' is set
        if ($organization_id === null || (is_array($organization_id) && count($organization_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_id when calling sysInvoiceDataSetsGetByInvoiceId'
            );
        }
        // verify the required parameter 'invoice_id' is set
        if ($invoice_id === null || (is_array($invoice_id) && count($invoice_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_id when calling sysInvoiceDataSetsGetByInvoiceId'
            );
        }

        $resourcePath = '/sysapi/v1.0/organizations/{organizationId}/invoicedatasets/{invoiceId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($organization_id !== null) {
            $resourcePath = str_replace(
                '{' . 'organizationId' . '}',
                ObjectSerializer::toPathValue($organization_id),
                $resourcePath
            );
        }
        // path params
        if ($invoice_id !== null) {
            $resourcePath = str_replace(
                '{' . 'invoiceId' . '}',
                ObjectSerializer::toPathValue($invoice_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceType
     *
     * Verkrijg een geaggregeerde dataset van facturen over een bepaalde periode
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_type  (required)
     * @param  \DateTime $start_date startdatum van de selectie periode (required)
     * @param  \DateTime $end_date einddatum van de selectie periode (required)
     * @param  string $invoice_sub_type Verplicht bij purchase facturen (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\EcedoERPCRMInterfaceApiInvoicesDataSetSummaryDto
     */
    public function sysInvoiceDataSetsGetByInvoiceType($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type)
    {
        list($response) = $this->sysInvoiceDataSetsGetByInvoiceTypeWithHttpInfo($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type);
        return $response;
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceTypeWithHttpInfo
     *
     * Verkrijg een geaggregeerde dataset van facturen over een bepaalde periode
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_type  (required)
     * @param  \DateTime $start_date startdatum van de selectie periode (required)
     * @param  \DateTime $end_date einddatum van de selectie periode (required)
     * @param  string $invoice_sub_type Verplicht bij purchase facturen (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\EcedoERPCRMInterfaceApiInvoicesDataSetSummaryDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function sysInvoiceDataSetsGetByInvoiceTypeWithHttpInfo($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type)
    {
        $returnType = '\Swagger\Client\Model\EcedoERPCRMInterfaceApiInvoicesDataSetSummaryDto';
        $request = $this->sysInvoiceDataSetsGetByInvoiceTypeRequest($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EcedoERPCRMInterfaceApiInvoicesDataSetSummaryDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EcedoERPCRMInterfaceApiErrorMessage400',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\EcedoERPCRMInterfaceApiErrorMessage401',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceTypeAsync
     *
     * Verkrijg een geaggregeerde dataset van facturen over een bepaalde periode
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_type  (required)
     * @param  \DateTime $start_date startdatum van de selectie periode (required)
     * @param  \DateTime $end_date einddatum van de selectie periode (required)
     * @param  string $invoice_sub_type Verplicht bij purchase facturen (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sysInvoiceDataSetsGetByInvoiceTypeAsync($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type)
    {
        return $this->sysInvoiceDataSetsGetByInvoiceTypeAsyncWithHttpInfo($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sysInvoiceDataSetsGetByInvoiceTypeAsyncWithHttpInfo
     *
     * Verkrijg een geaggregeerde dataset van facturen over een bepaalde periode
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_type  (required)
     * @param  \DateTime $start_date startdatum van de selectie periode (required)
     * @param  \DateTime $end_date einddatum van de selectie periode (required)
     * @param  string $invoice_sub_type Verplicht bij purchase facturen (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sysInvoiceDataSetsGetByInvoiceTypeAsyncWithHttpInfo($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type)
    {
        $returnType = '\Swagger\Client\Model\EcedoERPCRMInterfaceApiInvoicesDataSetSummaryDto';
        $request = $this->sysInvoiceDataSetsGetByInvoiceTypeRequest($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sysInvoiceDataSetsGetByInvoiceType'
     *
     * @param  string $organization_id  (required)
     * @param  string $invoice_type  (required)
     * @param  \DateTime $start_date startdatum van de selectie periode (required)
     * @param  \DateTime $end_date einddatum van de selectie periode (required)
     * @param  string $invoice_sub_type Verplicht bij purchase facturen (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sysInvoiceDataSetsGetByInvoiceTypeRequest($organization_id, $invoice_type, $start_date, $end_date, $invoice_sub_type)
    {
        // verify the required parameter 'organization_id' is set
        if ($organization_id === null || (is_array($organization_id) && count($organization_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $organization_id when calling sysInvoiceDataSetsGetByInvoiceType'
            );
        }
        // verify the required parameter 'invoice_type' is set
        if ($invoice_type === null || (is_array($invoice_type) && count($invoice_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_type when calling sysInvoiceDataSetsGetByInvoiceType'
            );
        }
        // verify the required parameter 'start_date' is set
        if ($start_date === null || (is_array($start_date) && count($start_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $start_date when calling sysInvoiceDataSetsGetByInvoiceType'
            );
        }
        // verify the required parameter 'end_date' is set
        if ($end_date === null || (is_array($end_date) && count($end_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $end_date when calling sysInvoiceDataSetsGetByInvoiceType'
            );
        }
        // verify the required parameter 'invoice_sub_type' is set
        if ($invoice_sub_type === null || (is_array($invoice_sub_type) && count($invoice_sub_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_sub_type when calling sysInvoiceDataSetsGetByInvoiceType'
            );
        }

        $resourcePath = '/sysapi/v1.0/organizations/{organizationId}/invoicetypes/{invoiceType}/invoicedatasets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($start_date !== null) {
            $queryParams['startDate'] = ObjectSerializer::toQueryValue($start_date);
        }
        // query params
        if ($end_date !== null) {
            $queryParams['endDate'] = ObjectSerializer::toQueryValue($end_date);
        }
        // query params
        if ($invoice_sub_type !== null) {
            $queryParams['invoiceSubType'] = ObjectSerializer::toQueryValue($invoice_sub_type);
        }

        // path params
        if ($organization_id !== null) {
            $resourcePath = str_replace(
                '{' . 'organizationId' . '}',
                ObjectSerializer::toPathValue($organization_id),
                $resourcePath
            );
        }
        // path params
        if ($invoice_type !== null) {
            $resourcePath = str_replace(
                '{' . 'invoiceType' . '}',
                ObjectSerializer::toPathValue($invoice_type),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
