<?php
/**
 * EcedoERPCRMInterfaceApiChargeSessionResultModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiChargeSessionResultModelTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiChargeSessionResultModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiChargeSessionResultModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiChargeSessionResultModel"
     */
    public function testEcedoERPCRMInterfaceApiChargeSessionResultModel()
    {
    }

    /**
     * Test attribute "charge_session_id"
     */
    public function testPropertyChargeSessionId()
    {
    }

    /**
     * Test attribute "external_session_id"
     */
    public function testPropertyExternalSessionId()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "measure_unit"
     */
    public function testPropertyMeasureUnit()
    {
    }

    /**
     * Test attribute "usage_type"
     */
    public function testPropertyUsageType()
    {
    }

    /**
     * Test attribute "usage_typelocalized"
     */
    public function testPropertyUsageTypelocalized()
    {
    }

    /**
     * Test attribute "cp_address"
     */
    public function testPropertyCpAddress()
    {
    }

    /**
     * Test attribute "cp_zip"
     */
    public function testPropertyCpZip()
    {
    }

    /**
     * Test attribute "cp_city"
     */
    public function testPropertyCpCity()
    {
    }

    /**
     * Test attribute "cp_country"
     */
    public function testPropertyCpCountry()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
