<?php
/**
 * EcedoERPCRMInterfaceApiContractPricesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiContractPricesTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiContractPrices
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiContractPricesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiContractPrices"
     */
    public function testEcedoERPCRMInterfaceApiContractPrices()
    {
    }

    /**
     * Test attribute "base_price_total_taxed"
     */
    public function testPropertyBasePriceTotalTaxed()
    {
    }

    /**
     * Test attribute "peak_price_total_taxed"
     */
    public function testPropertyPeakPriceTotalTaxed()
    {
    }

    /**
     * Test attribute "off_peak_price_total_taxed"
     */
    public function testPropertyOffPeakPriceTotalTaxed()
    {
    }
}
