<?php
/**
 * EcedoERPCRMInterfaceApiEvChargerCdrDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiEvChargerCdrDataTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiEvChargerCdrData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiEvChargerCdrDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiEvChargerCdrData"
     */
    public function testEcedoERPCRMInterfaceApiEvChargerCdrData()
    {
    }

    /**
     * Test attribute "connector_id"
     */
    public function testPropertyConnectorId()
    {
    }

    /**
     * Test attribute "cdr_id"
     */
    public function testPropertyCdrId()
    {
    }

    /**
     * Test attribute "time_start"
     */
    public function testPropertyTimeStart()
    {
    }

    /**
     * Test attribute "time_stop"
     */
    public function testPropertyTimeStop()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }

    /**
     * Test attribute "cp_address"
     */
    public function testPropertyCpAddress()
    {
    }

    /**
     * Test attribute "cp_zip"
     */
    public function testPropertyCpZip()
    {
    }

    /**
     * Test attribute "cp_city"
     */
    public function testPropertyCpCity()
    {
    }

    /**
     * Test attribute "cp_country"
     */
    public function testPropertyCpCountry()
    {
    }

    /**
     * Test attribute "cp_type"
     */
    public function testPropertyCpType()
    {
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "tariff_type"
     */
    public function testPropertyTariffType()
    {
    }

    /**
     * Test attribute "auth_id"
     */
    public function testPropertyAuthId()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "meter_id"
     */
    public function testPropertyMeterId()
    {
    }

    /**
     * Test attribute "cp_id"
     */
    public function testPropertyCpId()
    {
    }

    /**
     * Test attribute "cpo_id"
     */
    public function testPropertyCpoId()
    {
    }

    /**
     * Test attribute "total_cost"
     */
    public function testPropertyTotalCost()
    {
    }

    /**
     * Test attribute "add_energy_price"
     */
    public function testPropertyAddEnergyPrice()
    {
    }
}
