<?php
/**
 * EcedoERPCRMInterfaceServicesOCPIOcpiConnectorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceServicesOCPIOcpiConnectorTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceServicesOCPIOcpiConnector
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceServicesOCPIOcpiConnectorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceServicesOCPIOcpiConnector"
     */
    public function testEcedoERPCRMInterfaceServicesOCPIOcpiConnector()
    {
    }

    /**
     * Test attribute "connector_type"
     */
    public function testPropertyConnectorType()
    {
    }

    /**
     * Test attribute "power_type"
     */
    public function testPropertyPowerType()
    {
    }

    /**
     * Test attribute "connector_format"
     */
    public function testPropertyConnectorFormat()
    {
    }

    /**
     * Test attribute "evse_id"
     */
    public function testPropertyEvseId()
    {
    }

    /**
     * Test attribute "emi3_id"
     */
    public function testPropertyEmi3Id()
    {
    }

    /**
     * Test attribute "voltage"
     */
    public function testPropertyVoltage()
    {
    }

    /**
     * Test attribute "amperage"
     */
    public function testPropertyAmperage()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "power"
     */
    public function testPropertyPower()
    {
    }
}
