<?php
/**
 * EcedoERPCRMInterfaceApiFullEvChargerResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiFullEvChargerResultTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiFullEvChargerResult
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiFullEvChargerResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiFullEvChargerResult"
     */
    public function testEcedoERPCRMInterfaceApiFullEvChargerResult()
    {
    }

    /**
     * Test attribute "ev_charger_id"
     */
    public function testPropertyEvChargerId()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "client_reference"
     */
    public function testPropertyClientReference()
    {
    }

    /**
     * Test attribute "ocpi_location_id"
     */
    public function testPropertyOcpiLocationId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "installation_date"
     */
    public function testPropertyInstallationDate()
    {
    }

    /**
     * Test attribute "white_list"
     */
    public function testPropertyWhiteList()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }

    /**
     * Test attribute "evses"
     */
    public function testPropertyEvses()
    {
    }

    /**
     * Test attribute "ocpi_details"
     */
    public function testPropertyOcpiDetails()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }
}
