<?php
/**
 * EcedoERPCRMInterfaceApiChargeSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiChargeSessionTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiChargeSession
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiChargeSessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiChargeSession"
     */
    public function testEcedoERPCRMInterfaceApiChargeSession()
    {
    }

    /**
     * Test attribute "charge_id"
     */
    public function testPropertyChargeId()
    {
    }

    /**
     * Test attribute "start_datetime"
     */
    public function testPropertyStartDatetime()
    {
    }

    /**
     * Test attribute "end_datetime"
     */
    public function testPropertyEndDatetime()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {
    }

    /**
     * Test attribute "charge_location_type"
     */
    public function testPropertyChargeLocationType()
    {
    }

    /**
     * Test attribute "charge_location_organization_reference"
     */
    public function testPropertyChargeLocationOrganizationReference()
    {
    }

    /**
     * Test attribute "charge_location_connection_reference"
     */
    public function testPropertyChargeLocationConnectionReference()
    {
    }

    /**
     * Test attribute "service_provider_organization_reference"
     */
    public function testPropertyServiceProviderOrganizationReference()
    {
    }

    /**
     * Test attribute "infra_organization_reference"
     */
    public function testPropertyInfraOrganizationReference()
    {
    }

    /**
     * Test attribute "direct_pay_transaction_id"
     */
    public function testPropertyDirectPayTransactionId()
    {
    }

    /**
     * Test attribute "payment_type"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "cp_address"
     */
    public function testPropertyCpAddress()
    {
    }

    /**
     * Test attribute "cp_zip"
     */
    public function testPropertyCpZip()
    {
    }

    /**
     * Test attribute "cp_city"
     */
    public function testPropertyCpCity()
    {
    }

    /**
     * Test attribute "cp_country"
     */
    public function testPropertyCpCountry()
    {
    }

    /**
     * Test attribute "cp_id"
     */
    public function testPropertyCpId()
    {
    }

    /**
     * Test attribute "cpo_id"
     */
    public function testPropertyCpoId()
    {
    }
}
