<?php
/**
 * EcedoERPCRMInterfaceApiEvChargerPostDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiEvChargerPostDataTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiEvChargerPostData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiEvChargerPostDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiEvChargerPostData"
     */
    public function testEcedoERPCRMInterfaceApiEvChargerPostData()
    {
    }

    /**
     * Test attribute "evses"
     */
    public function testPropertyEvses()
    {
    }

    /**
     * Test attribute "service_contracts"
     */
    public function testPropertyServiceContracts()
    {
    }

    /**
     * Test attribute "evse_contract_data"
     */
    public function testPropertyEvseContractData()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "ev_charger_charging_capability"
     */
    public function testPropertyEvChargerChargingCapability()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "installation_party"
     */
    public function testPropertyInstallationParty()
    {
    }

    /**
     * Test attribute "power"
     */
    public function testPropertyPower()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "client_reference"
     */
    public function testPropertyClientReference()
    {
    }

    /**
     * Test attribute "connection_ean"
     */
    public function testPropertyConnectionEan()
    {
    }

    /**
     * Test attribute "has_card_reader"
     */
    public function testPropertyHasCardReader()
    {
    }

    /**
     * Test attribute "has_plug_charge"
     */
    public function testPropertyHasPlugCharge()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }
}
