<?php
/**
 * EcedoERPCRMInterfaceApiPassiveFlexSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EcedoERPCRMInterfaceApiPassiveFlexSessionTest Class Doc Comment
 *
 * @category    Class
 * @description EcedoERPCRMInterfaceApiPassiveFlexSession
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcedoERPCRMInterfaceApiPassiveFlexSessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcedoERPCRMInterfaceApiPassiveFlexSession"
     */
    public function testEcedoERPCRMInterfaceApiPassiveFlexSession()
    {
    }

    /**
     * Test attribute "feed_into_volume"
     */
    public function testPropertyFeedIntoVolume()
    {
    }

    /**
     * Test attribute "take_from_volume"
     */
    public function testPropertyTakeFromVolume()
    {
    }

    /**
     * Test attribute "measure_unit"
     */
    public function testPropertyMeasureUnit()
    {
    }

    /**
     * Test attribute "time_start"
     */
    public function testPropertyTimeStart()
    {
    }

    /**
     * Test attribute "time_stop"
     */
    public function testPropertyTimeStop()
    {
    }
}
