<?php
/**
 * SysCdrApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SysCdrApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SysCdrApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for sysCdrGetByChargeSessionId
     *
     * .
     *
     */
    public function testSysCdrGetByChargeSessionId()
    {
    }

    /**
     * Test case for sysCdrGetByExternalChargeSessionId
     *
     * .
     *
     */
    public function testSysCdrGetByExternalChargeSessionId()
    {
    }

    /**
     * Test case for sysCdrPost
     *
     * Aanmaken CDR records.
     *
     */
    public function testSysCdrPost()
    {
    }

    /**
     * Test case for sysCdrPostPassiveSmartCdr
     *
     * Aanmaken passieve onbalans laadsessies (passive Imbalance Flex Detail Records).
     *
     */
    public function testSysCdrPostPassiveSmartCdr()
    {
    }

    /**
     * Test case for sysCdrPostSmartCdr
     *
     * Aanmaken sessie's voor Onbalans Flex producten.
     *
     */
    public function testSysCdrPostSmartCdr()
    {
    }
}
