<?php
/**
 * SysEvChargerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ecedo.ERP.UI.Web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.22
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SysEvChargerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SysEvChargerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for sysEvChargerAddChargeCards
     *
     * Toevoegen passen aan bestaande laadpaal.
     *
     */
    public function testSysEvChargerAddChargeCards()
    {
    }

    /**
     * Test case for sysEvChargerAddConnector
     *
     * Toevoegen connector aan Evse.
     *
     */
    public function testSysEvChargerAddConnector()
    {
    }

    /**
     * Test case for sysEvChargerAddContract
     *
     * Toevoegen laadpaalcontract aan Evse.
     *
     */
    public function testSysEvChargerAddContract()
    {
    }

    /**
     * Test case for sysEvChargerAddServiceContract
     *
     * Toevoegen van een servicecontract aan een laadpaal.
     *
     */
    public function testSysEvChargerAddServiceContract()
    {
    }

    /**
     * Test case for sysEvChargerDeleteChargeCards
     *
     * Verwijderen passen van bestaande laadpaal.
     *
     */
    public function testSysEvChargerDeleteChargeCards()
    {
    }

    /**
     * Test case for sysEvChargerEvChargerProperties
     *
     * Wijzigen laadpaal property.
     *
     */
    public function testSysEvChargerEvChargerProperties()
    {
    }

    /**
     * Test case for sysEvChargerGetByOrganization
     *
     * Laadpalen per organisatie.
     *
     */
    public function testSysEvChargerGetByOrganization()
    {
    }

    /**
     * Test case for sysEvChargerGetChargeSessions
     *
     * Get charge sessions for a given EVSE in a given period.
     *
     */
    public function testSysEvChargerGetChargeSessions()
    {
    }

    /**
     * Test case for sysEvChargerGetChargeSessionsForEvCharger
     *
     * Get chargesessions for a given EvCharger in a period.
     *
     */
    public function testSysEvChargerGetChargeSessionsForEvCharger()
    {
    }

    /**
     * Test case for sysEvChargerGetEvChargerContracts
     *
     * Verkrijgen van alle contracten behorend bij een laadpaal.
     *
     */
    public function testSysEvChargerGetEvChargerContracts()
    {
    }

    /**
     * Test case for sysEvChargerGetEvChargerServiceContracts
     *
     * .
     *
     */
    public function testSysEvChargerGetEvChargerServiceContracts()
    {
    }

    /**
     * Test case for sysEvChargerGetSpecific
     *
     * Eén specifieke laadpaal.
     *
     */
    public function testSysEvChargerGetSpecific()
    {
    }

    /**
     * Test case for sysEvChargerPost
     *
     * Toevoegen laapaal.
     *
     */
    public function testSysEvChargerPost()
    {
    }

    /**
     * Test case for sysEvChargerPut
     *
     * Wijzigen laapaal.
     *
     */
    public function testSysEvChargerPut()
    {
    }

    /**
     * Test case for sysEvChargerUpdateEvseProperty
     *
     * Update EVSE property GuestUsageAllowed.
     *
     */
    public function testSysEvChargerUpdateEvseProperty()
    {
    }
}
